const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const menu=$(".menuBtn"),nav=$(".topbar nav");menu?.addEventListener("click",()=>nav.classList.toggle("open"));$$(".topbar nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
const gate=$("#gate"),enter=$("#enter"),audio=$("#baggageAudio"),dock=$("#audioDock"),toggle=$("#audioToggle"),clock=$("#audioTime");
function enterWorld(){sessionStorage.setItem("ra-entered","1");if(gate){gate.style.transition="opacity .65s";gate.style.opacity="0";setTimeout(()=>gate.remove(),680)}dock?.classList.add("show");if(audio){audio.volume=.72;audio.play().then(()=>{dock.classList.remove("paused");toggle.textContent="❚❚"}).catch(()=>{dock.classList.add("paused");toggle.textContent="▶"})}}
if(gate&&sessionStorage.getItem("ra-entered")){gate.remove();dock?.classList.add("show")}enter?.addEventListener("click",enterWorld);
toggle?.addEventListener("click",()=>{if(audio.paused){audio.play();toggle.textContent="❚❚";dock.classList.remove("paused")}else{audio.pause();toggle.textContent="▶";dock.classList.add("paused")}});
audio?.addEventListener("timeupdate",()=>{let s=Math.floor(audio.currentTime||0);clock.textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`});
$$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{let el=$(a.getAttribute("href"));if(el){e.preventDefault();el.scrollIntoView({behavior:"smooth",block:"start"})}}));
const screen=$("#movieScreen"),title=$("#movieTitle"),tag=$("#movieTag");$$(".film[data-youtube]").forEach(b=>b.addEventListener("click",()=>{$$(".film").forEach(x=>x.classList.remove("active"));b.classList.add("active");title.textContent=b.dataset.title;tag.textContent=b.dataset.tag;screen.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${b.dataset.youtube}?autoplay=1&rel=0" title="${b.dataset.title}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;screen.scrollIntoView({behavior:"smooth",block:"center"})}));
const sections=$$("#music,#cinema,#shop,#photos,#about,#contact"),links=$$(".topbar nav a");const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-30% 0px -60% 0px"});sections.forEach(s=>io.observe(s));
const cinema=$("#cinema");if(cinema)new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)cinema.classList.add("open")}),{threshold:.12}).observe(cinema);
const topBtn=$(".toTop");addEventListener("scroll",()=>topBtn.classList.toggle("show",scrollY>900),{passive:true});topBtn.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
function tokyoTime(){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date())}function tick(){let s=$("#tokyoStatus");if(!s.dataset.weather)s.textContent=`TOKYO // ${tokyoTime()}`}tick();setInterval(tick,30000);
async function weather(){let s=$("#tokyoStatus"),fx=$("#weatherFx");try{let r=await fetch("https://api.open-meteo.com/v1/forecast?latitude=35.6762&longitude=139.6503&current=temperature_2m,weather_code,precipitation,rain&timezone=Asia%2FTokyo"),d=await r.json(),c=d.current||{},code=+c.weather_code,rain=+(c.rain||c.precipitation||0),label="CLEAR",cls="clear";if(rain>0||[51,53,55,56,57,61,63,65,66,67,80,81,82,95,96,99].includes(code)){label="RAIN";cls="rain"}else if([1,2,3,45,48].includes(code)){label=code>=45?"MIST":"CLOUDY";cls="mist"}s.dataset.weather="1";s.textContent=`TOKYO // ${tokyoTime()} // ${label} ${Math.round(c.temperature_2m||0)}°C`;fx.className=`weather-fx ${cls}`}catch(e){}}weather();setInterval(weather,900000);
// Pull official release artwork at runtime from Apple's public iTunes Search API. Local covers remain as fallbacks.
async function hydrateArtwork(){for(const card of $$("#releaseRail article[data-search]")){if(card.querySelector("img"))continue;try{const q=encodeURIComponent(card.dataset.search);const r=await fetch(`https://itunes.apple.com/search?term=${q}&entity=album&limit=8`);const d=await r.json();const wanted=card.querySelector("b").textContent.toLowerCase();let hit=(d.results||[]).find(x=>(x.artistName||"").toLowerCase().includes("ra tha god")&&((x.collectionName||"").toLowerCase().includes(wanted)||wanted.includes((x.collectionName||"").toLowerCase())));if(!hit)hit=(d.results||[]).find(x=>(x.artistName||"").toLowerCase().includes("ra tha god"));if(hit?.artworkUrl100){let url=hit.artworkUrl100.replace("100x100bb","600x600bb");let img=document.createElement("img");img.src=url;img.alt=card.querySelector("b").textContent+" cover art";card.querySelector(".coverLoading")?.replaceWith(img)}}catch(e){}}}hydrateArtwork();
// V6 subway progress + photo alley + cursor atmosphere
const metroLinks=$$(".metroRail a");
const metroSections=[["top",document.querySelector(".hero")],["music",$("#music")],["cinema",$("#cinema")],["shop",$("#shop")],["photos",$("#photos")],["about",$("#about")],["contact",$("#contact")]];
const metroObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const found=metroSections.find(x=>x[1]===e.target);if(found)metroLinks.forEach(a=>a.classList.toggle("active",a.dataset.stop===found[0]))}}),{rootMargin:"-38% 0px -52% 0px"});
metroSections.forEach(x=>x[1]&&metroObs.observe(x[1]));
const glow=$(".cursorGlow");if(glow&&matchMedia("(hover:hover) and (pointer:fine)").matches)addEventListener("pointermove",e=>{glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px"},{passive:true});
const lightbox=$("#photoLightbox"),lbImg=lightbox?.querySelector("img"),lbCap=lightbox?.querySelector("span");
$$(".photos figure").forEach(f=>f.addEventListener("click",()=>{lbImg.src=f.querySelector("img").src;lbImg.alt=f.querySelector("img").alt||"";lbCap.textContent=f.querySelector("figcaption")?.textContent||"";lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false")}));
function closeLB(){lightbox?.classList.remove("open");lightbox?.setAttribute("aria-hidden","true")}
lightbox?.querySelector("button")?.addEventListener("click",closeLB);lightbox?.addEventListener("click",e=>{if(e.target===lightbox)closeLB()});addEventListener("keydown",e=>{if(e.key==="Escape")closeLB()});
