const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const menu=$(".menuBtn"),nav=$(".topbar nav");menu?.addEventListener("click",()=>nav.classList.toggle("open"));$$(".topbar nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
const gate=$("#gate"),enter=$("#enter"),audio=$("#baggageAudio"),dock=$("#audioDock"),toggle=$("#audioToggle"),clock=$("#audioTime");
function enterWorld(){sessionStorage.setItem("ra-entered","1");if(gate){gate.style.transition="opacity .65s,filter .65s";gate.style.opacity="0";gate.style.filter="blur(14px)";setTimeout(()=>gate.remove(),680)}dock?.classList.add("show");if(audio){audio.volume=.72;audio.play().then(()=>{dock.classList.remove("paused");toggle.textContent="❚❚"}).catch(()=>{dock.classList.add("paused");toggle.textContent="▶"})}}
if(gate&&sessionStorage.getItem("ra-entered")){gate.remove();dock?.classList.add("show")}enter?.addEventListener("click",enterWorld);
toggle?.addEventListener("click",()=>{if(audio.paused){audio.play();toggle.textContent="❚❚";dock.classList.remove("paused")}else{audio.pause();toggle.textContent="▶";dock.classList.add("paused")}});
audio?.addEventListener("timeupdate",()=>{let s=Math.floor(audio.currentTime||0);clock.textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`});
$$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{let el=$(a.getAttribute("href"));if(el){e.preventDefault();el.scrollIntoView({behavior:"smooth",block:"start"})}}));
const screen=$("#movieScreen"),title=$("#movieTitle"),tag=$("#movieTag");$$(".film[data-youtube]").forEach(b=>b.addEventListener("click",()=>{$$(".film").forEach(x=>x.classList.remove("active"));b.classList.add("active");title.textContent=b.dataset.title;tag.textContent=b.dataset.tag;screen.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${b.dataset.youtube}?autoplay=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;screen.scrollIntoView({behavior:"smooth",block:"center"})}));
const links=$$(".topbar nav a");new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-30% 0px -60% 0px"}).observe($("#music"));["cinema","shop","photos","about","contact"].forEach(id=>{const el=$("#"+id);if(el)new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+id))}),{rootMargin:"-30% 0px -60% 0px"}).observe(el)});
const topBtn=$(".toTop");addEventListener("scroll",()=>topBtn.classList.toggle("show",scrollY>900),{passive:true});topBtn.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
function tokyoTime(){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date())}function tick(){let s=$("#tokyoStatus");if(!s.dataset.weather)s.textContent=`TOKYO // ${tokyoTime()}`}tick();setInterval(tick,30000);
async function weather(){let s=$("#tokyoStatus"),fx=$("#weatherFx");try{let r=await fetch("https://api.open-meteo.com/v1/forecast?latitude=35.6762&longitude=139.6503&current=temperature_2m,weather_code,precipitation,rain&timezone=Asia%2FTokyo"),d=await r.json(),c=d.current||{},code=+c.weather_code,rain=+(c.rain||c.precipitation||0),label="CLEAR",cls="clear";if(rain>0||[51,53,55,56,57,61,63,65,66,67,80,81,82,95,96,99].includes(code)){label="RAIN";cls="rain"}else if([1,2,3,45,48].includes(code)){label=code>=45?"MIST":"CLOUDY";cls="mist"}s.dataset.weather="1";s.textContent=`TOKYO // ${tokyoTime()} // ${label} ${Math.round(c.temperature_2m||0)}°C`;fx.className=`weather-fx ${cls}`}catch(e){}}weather();setInterval(weather,900000);